#!/usr/bin/env bash
# install-personal-extras.sh — personal-branch-only installer.
# Wires handoff/resume skills + Codex shortcut scripts for cross-vendor
# session continuity (Claude Code ↔ Codex).
#
# Do NOT run this on a work machine. Governance-sensitive.
set -euo pipefail

CLAUDE_DIR="${CLAUDE_DIR:-$HOME/.claude}"
CODEX_DIR="${CODEX_DIR:-$HOME/.codex}"
TOOLKIT_DIR="${TOOLKIT_DIR:-$HOME/.cache/ai-dev-toolkit}"

log() { printf '[personal-extras] %s\n' "$*"; }
skip() { printf '[personal-extras] skip: %s\n' "$*"; }

install_handoff_skills() {
  local src_dir="$TOOLKIT_DIR/kit/core/skills"
  local dest_dir="$CLAUDE_DIR/skills"

  if [[ ! -d "$src_dir" ]]; then
    skip "toolkit not found at $src_dir — run ./bootstrap.sh first"
    return 0
  fi

  mkdir -p "$dest_dir"
  for skill in handoff-system.md resume.md; do
    local src="$src_dir/$skill"
    local dest="$dest_dir/$skill"
    if [[ -f "$src" ]]; then
      ln -sf "$src" "$dest"
      log "linked $skill"
    else
      skip "$skill not in toolkit (personal-branch only asset)"
    fi
  done
}

install_codex_shortcuts() {
  if [[ ! -d "$CODEX_DIR" ]]; then
    skip "$CODEX_DIR not found — install codex CLI first"
    return 0
  fi

  local scripts_dir="$CODEX_DIR/scripts"
  mkdir -p "$scripts_dir"

  for script in rag-recall rag-pack spec aggregate-roadmap claude-handoff; do
    local dest="$scripts_dir/${script}.sh"
    if [[ -f "$dest" ]]; then
      skip "${script}.sh already present"
      continue
    fi
    cat >"$dest" <<EOF
#!/usr/bin/env bash
# Generated by install-personal-extras.sh.
# Routes to the shared RAG + specs venv installed by install-rag.sh.
exec "\$HOME/.claude/rag-index/scripts/${script}.sh" "\$@"
EOF
    chmod +x "$dest"
    log "created codex/scripts/${script}.sh"
  done
}

main() {
  log "installing personal extras (handoff skills + Codex shortcuts)"
  install_handoff_skills
  install_codex_shortcuts
  log "done — governance-sensitive: do not run on a work machine"
}

main "$@"
